import type { Project } from "../lib/types";

export const projects: Project[] = [
  {
    id: "birthday-calendar",
    year: "2026",
    thumbnail: "/web/birthday.png",
    video: "/web/birthday.webm",
    category: "web",
    links: [{ type: "Web", url: "https://p2j-calender.vercel.app/" }],
    skills: [
      "React",
      "Next.js",
      "TailwindCSS",
      "Google Calendar API",
      "Restful API",
      "Figma",
      "Notion",
      "UI/UX",
      "使用者故事",
      "流程圖",
      "Web",
    ],
  },
  {
    id: "warrant-landing-page",
    year: "2026",
    thumbnail: "/web/warrentlp.webp",
    category: "web",
    links: [{ type: "Web", url: "https://warrantlb8888.cmoney.tw/" }],
    skills: [
      "React",
      "Next.js",
      "TailwindCSS",
      "Figma",
      "Jira",
      "UI/UX",
      "SEO",
      "使用者故事",
      "流程圖",
      "Web",
    ],
  },
  {
    id: "longterm-treasure-app",
    year: "2026",
    thumbnail: "/web/longterm.webp",
    video: "/web/longterm-app.webm",
    category: "app",
    images: ["/web/longterm.webp", "/web/longterm.webp", "/web/longterm.webp"],
    links: [
      {
        type: "App Store",
        url: "https://apps.apple.com/lb/app/%E9%95%B7%E7%B7%9A%E8%81%9A%E5%AF%B6%E7%9B%86plus/id6760089358",
      },
      {
        type: "Google Play",
        url: "https://play.google.com/store/apps/details?id=com.cmoney.linenrulongterm",
      },
    ],
    skills: ["Jira", "Notion", "Confluence", "Swimlane", "使用者故事", "流程圖"],
  },
  {
    id: "longterm-treasure-web",
    year: "2026",
    thumbnail: "/web/longterm.webp",
    video: "/web/longterm-web.webm",
    category: "web",
    links: [
      { type: "Web", url: "https://imoney889.cmoney.tw/web/longterm/" },
    ],
    skills: [
      "React",
      "Next.js",
      "TailwindCSS",
      "Figma",
      "Jira",
      "UI/UX",
      "使用者故事",
      "流程圖",
      "Web",
    ],
  },
  {
    id: "simple-futures-web",
    year: "2026",
    thumbnail: "/web/simple-futures.webp",
    video: "/web/simple-futures.webm",
    category: "web",
    links: [
      { type: "Web", url: "https://imoney889.cmoney.tw/software/futures" },
    ],
    skills: [
      "React",
      "Next.js",
      "TailwindCSS",
      "Figma",
      "Jira",
      "UI/UX",
      "使用者故事",
      "流程圖",
      "Web",
    ],
  },
  {
    id: "gamified-weight-loss",
    year: "2025",
    video: "/web/gobetgoal.webm",
    thumbnail: "/web/gamified-weight-loss.webp",
    category: "",
    links: [
      { type: "GitHub", url: "https://github.com/TooruTW/GoBetGoal" },
      { type: "Web", url: "https://gobetgoal.vercel.app/" },
    ],
    skills: [
      "React",
      "Redux",
      "TanStack",
      "Shadcn",
      "GSAP",
      "Lottie",
      "Swiper",
      "TailwindCSS",
      "Figma",
      "Playwright",
      "Supabase",
      "UI/UX",
      "Git",
      "Jira",
      "Notion",
      "Swimlane",
      "Confluence",
      "Photoshop",
      "Illustrator",
      "使用者故事",
      "易用性測試",
      "Gemini",
      "Cursor",
    ],
  },
  {
    id: "hotel-website",
    year: "2025",
    video: "/web/hotelbooking.webm",
    thumbnail: "/web/hotel-website.webp",
    category: "",
    links: [
      { type: "GitHub", url: "https://github.com/sunny2001522/Hotel-booking" },
      { type: "Web", url: "https://iceverse-hotel-booking.vercel.app/" },
    ],
    skills: [
      "React",
      "TailwindCSS",
      "MongoDB",
      "Restful API",
      "Figma",
      "Git",
      "Photoshop",
      "Illustrator",
      "UI/UX",
    ],
  },
  {
    id: "portfolio",
    year: "2025",
    thumbnail: "/web/portfolio.webp",
    video: "/web/portfolio.webm",
    category: "",
    links: [
      { type: "GitHub", url: "https://github.com/sunny2001522/Portfolio" },
      { type: "Web", url: "https://exuan-website-dev.vercel.app/zh" },
    ],
    skills: [
      "Next.js",
      "TailwindCSS",
      "GSAP",
      "i18n",
      "Git",
      "Figma",
      "Swiper",
      "Spline",
      "Photoshop",
      "Illustrator",
      "UI/UX",
    ],
  },
  {
    id: "metro-app",
    year: "2025",
    thumbnail: "/web/metro-app.webp",
    category: "design",
    links: [],
    skills: ["Figma", "Photoshop", "Illustrator", "UI/UX"],
  },
  {
    id: "ai-customer-service",
    year: "2026",
    thumbnail: "/web/lp.webp",
    category: "web",
    links: [
      { type: "Web", url: "https://imoney889.cmoney.tw/" },
    ],
    skills: [
      "React",
      "Next.js",
      "TailwindCSS",
      "Gemini",
      "Figma",
      "Jira",
      "UI/UX",
      "使用者故事",
      "流程圖",
      "Web",
    ],
  },
  {
    id: "social-media-tool",
    year: "2026",
    thumbnail: "/web/post.webp",
    video: "/web/mediapost.webm",
    category: "web",
    links: [
      { type: "Web", url: "https://mediapost-t5gjnmk2qq-de.a.run.app" },
    ],
    skills: [
      "React",
      "Redux",
      "TanStack",
      "TailwindCSS",
      "Notion",
      "Figma",
      "UI/UX",
      "使用者故事",
      "泳道圖",
    ],
  },
  {
    id: "ai-data-analysis",
    year: "2025",
    thumbnail: "/web/data.webp",
    video: "/web/analytics.webm",
    category: "web",
    links: [],
    skills: [
      "React",
      "Next.js",
      "TailwindCSS",
      "Cursor",
      "Figma",
      "Jira",
      "UI/UX",
      "流程圖",
    ],
  },
  {
    id: "ai-co-writing",
    year: "2025",
    thumbnail: "/web/genink.webp",
    video: "/web/genink.webm",
    category: "web",
    links: [{ type: "Web", url: "https://gen-ink.vercel.app/" }],
    skills: [
      "React",
      "TailwindCSS",
      "Gemini",
      "Figma",
      "Notion",
      "UI/UX",
      "使用者故事",
    ],
  },
  {
    id: "ai-video-content-generation",
    year: "2025",
    thumbnail: "/web/dreamake.webp",
    video: "/web/dreammake.webm",
    category: "web",
    links: [
      { type: "Web", url: "https://www.dreamake.ai/" },
    ],
    skills: [
      "Next.js",
      "TailwindCSS",
      "Figma",
      "Jira",
      "UI/UX",
      "流程圖",
      "易用性測試",
      "Render",
    ],
  },
  {
    id: "book",
    year: "2024",
    thumbnail: "/design/book.webp",
    category: "design",
    links: [],
    skills: ["Photoshop", "Illustrator", "UI/UX"],
  },
  {
    id: "iceverse",
    year: "2024",
    thumbnail: "/design/iceverse.webp",
    category: "design",
    links: [],
    skills: ["Photoshop", "Illustrator", "UI/UX"],
  },
  {
    id: "iceverseProduct",
    year: "2024",
    thumbnail: "/design/iceverseProduct.webp",
    category: "design",
    links: [],
    skills: ["Photoshop", "Illustrator", "UI/UX"],
  },
  {
    id: "actor",
    year: "2024",
    thumbnail: "/design/actor.webp",
    category: "design",
    links: [],
    skills: ["Photoshop", "Illustrator", "UI/UX"],
  },
  {
    id: "taipei",
    year: "2024",
    thumbnail: "/design/taipei.webp",
    category: "design",
    links: [],
    skills: ["Photoshop", "Illustrator", "UI/UX"],
  },
];
